version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    image: <-name->:<tag>
    restart: always 
    networks:
      - webnet
networks:
  webnet:

# docker-compose build
# docker-compose up 