apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
        labels:
          app: myapp
    spec:
      containers:
      - name: webapp 
        image: josephquay/webapp:1.0
        resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
        ports:
          - containerPort: 5000
         
# add image name 